apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: swipeback
  name: swipeback
  namespace: sportswipe
spec:
  replicas: 1
  selector:
    matchLabels:
      service: swipeback
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service: swipeback
    spec:
      containers:
      - name: swipeback
        image: registry.goebel.app/jonas/hackathon-swipeback:6
        imagePullPolicy: ""
        envFrom:
          - secretRef:
              name: swipeback-env
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /var/www/html/firebaseconfig.json
          subPath: firebaseconfig.json
          name: firebaseconfig
      imagePullSecrets:
        - name: regcred
      restartPolicy: Always
      volumes:
      - name: firebaseconfig
        configMap:
          name: firebaseconfig
