apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: swipeback
  namespace: sportswipe
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  rules:
    - host: swipeback.fulda.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: swipeback
                port:
                  number: 80