apiVersion: v1
kind: Service
metadata:
  labels:
    service: swipeback
  name: swipeback
  namespace: sportswipe
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  selector:
    service: swipeback
status:
  loadBalancer: {}
